Add the interactive job type
cyverse-de/de-db pull request #28
Opened 2018-06-01 18:11 UTC by johnworth

2018-06-01 19:06 UTC, psarando commented on src/main/data/99_version.sql
> +INSERT INTO version (version) VALUES ('2.23.0:20180601.01');
`v2.21.0` conversions were just released in prod.
Shouldn't this conversion still be `v2.22.0`?

2018-06-01 19:07 UTC, johnworth commented
I have no idea.

On Fri, Jun 1, 2018 at 12:06 PM Paul Sarando <notifications@github.com>
wrote:

> *@psarando* commented on this pull request.
> ------------------------------
>
> In src/main/data/99_version.sql
> <https://github.com/cyverse-de/de-db/pull/28#discussion_r192488968>:
>
> > @@ -95,3 +95,4 @@ INSERT INTO version (version) VALUES ('2.21.0:20180419.01');
>  INSERT INTO version (version) VALUES ('2.21.0:20180426.01');
>  INSERT INTO version (version) VALUES ('2.21.0:20180515.01');
>  INSERT INTO version (version) VALUES ('2.22.0:20180523.01');
> +INSERT INTO version (version) VALUES ('2.23.0:20180601.01');
>
> v2.21.0 conversions were just released in prod.
> Shouldn't this conversion still be v2.22.0?
>
> —
> You are receiving this because you authored the thread.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cyverse-de/de-db/pull/28#pullrequestreview-125284321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AADCd6aRusOb7wBkU7hBqR0R4X93TV5uks5t4ZDNgaJpZM4UXG4E>
> .
>

2018-06-01 19:11 UTC, psarando requested changes
I think this conversion should be for `v2.22.0`.

2018-06-01 19:11 UTC, psarando commented on src/main/conversions/v2.23.0/c2_23_0_2018060101.clj
> +(ns facepalm.c2-23-0-2018060101
To put it another way: I think this conversion should be `v2.22.0`, unless there's a reason this PR shouldn't be merged until the release after next...

2018-06-01 19:21 UTC, psarando approved these changes

2018-06-02 01:10 UTC, slr71 approved these changes
LGTM :shipit:

2018-06-02 01:12 UTC, slr71 commented
I'm going to be evil and merge these changes now. 😈

2018-06-02 01:12 UTC, merged