CORE-63: add an htcondor_extra_requirements column
cyverse-de/de-db pull request #40
Opened 2019-02-06 21:05 UTC by ianmcorvidae

This will store extra things to be added to the job requirements at the
app level. This should only be editable by administrators, and will be
joined to the requirements we manage manually by way of an &&.

I pretty much just copied another conversion, so hopefully I didn't do something wrong there, heh.

2019-02-06 23:06 UTC, ianmcorvidae commented
The other approach I could take here, and I'm tempted by it, is to shove this in a side table instead. Which might provide a nicer means of not polluting app listings with this? Dunno?

2019-02-19 20:59 UTC, psarando requested changes
LGTM. We just need a new entry in the `versions` data file, for freshly initialized dbs.

2019-02-19 20:59 UTC, psarando commented on src/main/conversions/v2.25.0/c2_25_0_2019020601.clj
> +  "2.25.0:20190206.01")
We also have to add this verison to the `src/main/data/99_version.sql` file, for new databases.
```sql
INSERT INTO version (version) VALUES ('2.25.0:20190206.01');
```

2019-02-20 00:48 UTC, psarando commented
> The other approach I could take here, and I'm tempted by it, is to shove this in a side table instead. Which might provide a nicer means of not polluting app listings with this?

That sounds like a fine idea to me as well. It could also set us up with a pattern for expanding additional submission options for other job systems in the future (maybe they each get their own `_extra_requirements` tables? 🤷‍♂️).

2019-02-21 21:35 UTC, ianmcorvidae commented
Heh, that's a good point. I think I'll switch it to being a separate, dedicated table. It's not perfectly normalized, but... eh

2019-02-21 21:49 UTC, psarando approved these changes

2019-02-22 00:28 UTC, ianmcorvidae commented
I also see that now there's another conversion (dropping collaborators table) that got merged in before this. I'm not sure if I should change the date on this conversion so they're in the order they got merged or not.

2019-02-22 00:31 UTC, psarando commented
> I also see that now there's another conversion (dropping collaborators table) that got merged in before this. I'm not sure if I should change the date on this conversion so they're in the order they got merged or not.

I don't think it matters either way, since these conversions don't operate on the same tables or data.

2019-02-22 00:34 UTC, slr71 commented
Hmm, the only reason I can see it making a difference is if the other conversion was applied before this one. The conversion files are applied in lexographical order, if I remember correctly, so this conversion might not be applied if the one to remove the collaborators table was applied in a different facepalm run.

I don't think that's going to happen, though. The collaborators table conversion has only been applied to QA, and we'll be refreshing the database in order to apply these changes anyway.

2019-02-22 00:36 UTC, psarando commented
> The collaborators table conversion has only been applied to QA, and we'll be refreshing the database in order to apply these changes anyway.

Good point. It would make a difference if the other conversion was already applied to production.

2019-02-22 20:23 UTC, merged

2019-02-22 20:24 UTC, ianmcorvidae commented
I'm going ahead and getting it merged in, then. I haven't done the apps service work, but, well, this is a benefit of it being another table too, heh :)

2019-02-22 20:24 UTC, ianmcorvidae commented
Thanks for the reviews!