Track the execution system for job steps.
cyverse-de/de-db pull request #5
Opened 2016-12-09 01:02 UTC by dennisroberts71

The inclusion of the system ID in job submissions means that we must associate the remote system ID with steps in a pipeline. The execution of mixed pipelines is also easier to manage when the remote system ID is associated with each step in the `job_steps` table.

2016-12-09 23:25 UTC, psarando requested changes
If possible, it would be nice to get the `tasks` and `jobs` constraints cleaned up in this PR (since some are getting added). Otherwise, this PR looks good to me and I didn't catch any other issues 👍

2016-12-09 23:25 UTC, psarando commented on src/main/constraints/00_constraints.sql
> +    REFERENCES job_types(id);
We've been trying to move constraints out of this file and into separate files under the `constraints` folder. If possible, it would be better to move these (and any other `tasks` and `jobs` constraints) into their own files.

2016-12-09 23:25 UTC, psarando commented on src/main/constraints/57_jobs.sql
> +CREATE INDEX jobs_end_date_index ON jobs(end_date);
One of the advantages of these separate constraints files is that if any tables need to have their constraints reset, then all constraints can by dropped at once by a query and then reloaded from these files (this is what was done for the `v1.9.3` conversions).

Unfortunately indexes won't be dropped by a query like that, so reloading this file will probably cause an error when trying to create a duplicate index. This is the reason I have been putting these indexes in the `tables` definition scripts.

2016-12-12 18:40 UTC, dennisroberts71 commented on src/main/constraints/00_constraints.sql
> +    REFERENCES job_types(id);
Good suggestion! I'll make that change.

2016-12-12 18:40 UTC, dennisroberts71 commented on src/main/constraints/57_jobs.sql
> +CREATE INDEX jobs_end_date_index ON jobs(end_date);
Okay, thanks. I'll move the indexes back into the tables file.

2016-12-12 23:02 UTC, psarando approved these changes

2016-12-13 00:50 UTC, merged